TrainManagerService
TIS2023-FMFI/vlaky pull request #41
Opened 2023-12-17 17:07 UTC by dedinside1337

2023-12-17 18:25 UTC, Pia669 requested changes
- sql parameter ma tvar ($1) nie $1 (construktor)
- v DB stlpec date ma format date niesom si isty ci string bude fungovat

2023-12-17 19:27 UTC, jakino22 approved these changes
ok

2023-12-17 19:28 UTC, jakino22 approved these changes

2023-12-17 19:29 UTC, jakino22 approved these changes

2023-12-18 11:02 UTC, dedinside1337 commented
pridane WagonManagerService a upravene TrainManagerService

2023-12-18 21:27 UTC, Pia669 approved these changes

2023-12-18 21:27 UTC, merged